import 'package:flutter/material.dart';
class AppColors {
  static const primary = Color(0xFF4CA634);
  static const lightBackground = Colors.white;
  static const darkBackground = Colors.black;
  static const textBlack = Color(0xFF101828);
  static const textDarkBlack = Color(0xFF2B2B2B);
  static const textWhite = Color(0xFFFFFFFF);
  static const textGrey = Color(0xFF98A2B3);
  static const textDarkGrey = Color(0xFF344054);
  static const textNavyBlue = Color(0xFF133452);
  static const textAsh = Color(0xFF4F5464);
  static const textlightGreen = Color(0xFFD6FFCB);
  static const NavBarNavyBlue = Color(0xFF133452);
  static const NavyBlue = Color(0xFF133452);
  static const labelGrey = Color(0xFF475467);
  static const darkGreen = Color(0xFF19B36E);
  static const backgroundGrey = Color(0xFFF4F5FF);
  static const backgroundWhite = Color(0xFFFEFEFE);
  static const backgroundDarkGrey = Color(0xFFEBE9FE);
  static const containerBackgroundGrey100 = Color(0xFFF9FAFB);
  static const containerBackgroundGrey101 = Color(0xFFEBECEE);
  static const containerBackgroundGrey200 = Color(0xFFEEEEEE);
  static const containerBackgroundGrey300 = Color(0xFFEAECF0);
  static const containerBackgroundGrey400 = Color(0xFFF4F6F9);
  static const containerBackgroundRed = Color(0xFFF95555);
  static const containerBackgroundRed2 = Color(0xFFE50404);
  static const containerBackgroundGreen = Color(0xFF3FEF09);
  static const containerBackgroundYellow = Color(0xFFF79009);
  static const containerBackgroundPurple = Color(0xFFF4F3FF);
}